### ISSUE TITLE
Player 2 doesn't jump on 'Y'.

### ISSUE THREAD

**Issue by egomish** [IanGRap/Squish#22]
Description:
- Pressing the 'Y' button should make the player jump, but nothing happens when player 2 presses 'Y'.
    - Player 1 jumps on 'Y' as expected.
    - This happens no matter which controller is plugged in.

Reproduce Case:
- In a scene with two players and two controllers plugged in, press 'Y' on the player 2 controller.

Possible Problem:
Player 2 'Y' input isn't listed in the inputs.

**Comment by AustinKellar** [comment]
We fixed this when we added the inputs for players 3 and 4.
